version: 2.1
executors:
  coopctl:
    docker:
      - image: colabcoop/operator:0.0.31
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
jobs:
  deploy:
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: true
      - run:
          name: Deploy to CoLab Kube
          no_output_timeout: 30m
          command: deploy
workflows:
  deploy:
    jobs:
      - deploy:
          context: colab-kube-production-v1
          filters:
            branches:
              only: production
      - deploy:
          context: colab-kube-staging-v1
          filters:
            branches:
              only: staging
