repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
environments:
  production:
  staging:
releases:
  - name: colab-discourse
    namespace: colab
    chart: bitnami/discourse
    version: 6.0.2
    secrets:
      - vault: colab-discourse-app
        path: auth
      - vault: colab-discourse-db
        path: postgresql.auth
      - vault: colab-discourse-cache
        path: redis.auth
      - vault: colab-discourse-smtp
        path: smtp
    values:
      - ./values/env.yaml.gotmpl
      - ./values/{{.Environment.Name}}.yaml.gotmpl
