repositories:
  - name: colab
    url: https://colab-coop.github.io/helm-charts/charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
environments:
  production:
  staging:
releases:
  - name: hive-backup
    namespace: colab-hive
    chart: colab/backup-schedule
    version: 0.0.2
  - name: hive-app
    namespace: colab-hive
    chart: bitnami/discourse
    version: 7.0.2
    secrets:
      - vault: hive-app
        path: auth
      - vault: hive-db
        path: postgresql.auth
      - vault: hive-cache
        path: redis.auth
      - vault: hive-smtp
        path: smtp
    values:
      - ./values/env.yaml.gotmpl
      - ./values/{{.Environment.Name}}.yaml.gotmpl
