primary:
  persistence:
    size: 10Gi
    accessModes:
      - ReadWriteOnce
readReplicas:
  persistence:
    accessModes:
      - ReadWriteOnce
image:
  repository: bitnami/postgresql
  tag: 14.2.0
### Place those values in Vault
# global:
#   postgresql:
#     auth:
#       database: ""
#       username: ""
#       password: ""
#       postgresPassword: ""
