clusterDomain: "hive.kube.stage.colab.coop"
host: "hive.kube.stage.colab.coop"
ingress:
  hostname: "hive.kube.stage.colab.coop"
### Place those values in Vault
# smtp:
#   host: ""
#   user: ""
#   password: ""
# auth:
#   email: ""
#   username: ""
#   password: ""
# externalDatabase:
#   database: ""
#   user: ""
#   password: ""
#   postgresUser: ""
#   postgresPassword: ""
# externalRedis:
#   password: ""
